# Generated by Django 3.0.7 on 2020-08-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200823_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='demo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technology',
            field=models.CharField(max_length=100),
        ),
    ]
