# Generated by Django 3.0.7 on 2020-08-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200714_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
