# Generated by Django 3.0.7 on 2020-08-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_customtext3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
